### ISSUE TITLE
Cant logging real client ip

### ISSUE THREAD

**Issue by monkeyWie** [encode/uvicorn#1223]
I'm using nginx to reverse uvicorn server, the nginx conf like this:
```
location /api {
        proxy_pass http://127.0.0.1:28888;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```
and the uvicorn start command is `["uvicorn","app.main:app","--host","0.0.0.0","--proxy-headers","--forwarded-allow-ips='*'"]`,but I see that the log ip is still the local ip

![image](https://user-images.githubusercontent.com/13160176/138018170-940dce78-e42e-4c09-bde4-38b3d726e37f.png)

So what should I do?

Thanks~

**Comment by manlix** [comment]
Hi @monkeyWie

What IP address did you expect to see?

I think you use **Docker** or **Docker Compose** to run `nginx`. 

If it's so: `172.17.0.1` is correct IP address because your default network as `bridge` and your IP address is `172.17.0.1` (**gateway**) by default to connect to containers:

```
$ sudo docker network inspect bridge | jq ".[].IPAM.Config"
[
  {
    "Subnet": "172.17.0.0/16",
    "Gateway": "172.17.0.1"
  }
]
```

Try to use `host` network as workaround:

For **Docker**: `--network=host`
```
$ sudo docker run --network=host --rm -it IMAGE
```

For **Docker Compose**: `network_mode=host`
```
services:
  nginx:
  ...
  network_mode: host
```

But keep in mind in this case you use host network not isolated docker network.

**Comment by monkeyWie** [comment]
Actually my nginx is running at host machine and uvicorn server runing in docker, I use tcpdump capture http data that nginx reverse  request uvicorn server,like this:
![image](https://user-images.githubusercontent.com/13160176/138070644-e0dd7339-0493-4d44-80e0-0e5243f1eb43.png)

You can see that `X-Forwarded-For` is fine, but the uvicorn log ip is still `172.17.0.1`.

**Comment by manlix** [comment]
@monkeyWie  Thank you for details.

> ["uvicorn","app.main:app","--host","0.0.0.0","--proxy-headers","--forwarded-allow-ips='*'"]

Try to replace `"--forwarded-allow-ips='*'"` to `"--forwarded-allow-ips", "*"`:

```
["uvicorn","app.main:app","--host","0.0.0.0","--proxy-headers","--forwarded-allow-ips", "*"]
```

**Comment by monkeyWie** [comment]
@manlix Thank you ! the problem has been solved.
